namespace PremiumService.DTOs
{
    /// <summary>
    /// Represents the result of a payment transaction.
    /// </summary>
    public class PaymentResultDto
    {
        /// <summary>
        /// Payment ID.
        /// </summary>
        public int PaymentId { get; set; }

        /// <summary>
        /// Unique transaction ID generated by the payment gateway.
        /// </summary>
        public string TransactionId { get; set; } = string.Empty;

        /// <summary>
        /// Current payment status.
        /// Example: Success, Failed, Pending.
        /// </summary>
        public string PaymentStatus { get; set; } = string.Empty;

        /// <summary>
        /// Result message.
        /// </summary>
        public string Message { get; set; } = string.Empty;

    }
}
