spring.application.name=reownix

spring.datasource.url=jdbc:postgresql://localhost:6432/reownix_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud-name=smrc3gci
cloudinary.api-key=516533179916579
cloudinary.api-secret=UA-BB4fDxjoqpUDom8ciGJ9FXMY
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs