spring.application.name=app
spring.datasource.url=jdbc:postgresql://localhost:5432/reownix?createDatabaseIfNotExist=true

spring.datasource.username=postgres

spring.datasource.password=Nikita@1905

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

#jwt authentication 
jwt.secret=ThisIsMyVerySecretKeyForReOwnXProject12345678901234567890
jwt.expiration=86400000

# cloudinary
cloudinary.cloud-name=ccmkbpxl
cloudinary.api-key=794373632379635
cloudinary.api-secret=PoGs-EuKSreKOLaW6ild18hRI9s

# WebSocket & STOMP Debugging
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.reownix=DEBUG