import axios from 'axios';

// ============================================================================
// ASP.NET Core Premium Service API Client
// ============================================================================
// This Axios instance is dedicated EXCLUSIVELY to the ASP.NET Core backend
// running on port 5243. It does not interfere with the Spring Boot APIs.
// ============================================================================

const dotnetApi = axios.create({
  baseURL: 'http://localhost:5243/api',
  headers: {
    'Content-Type': 'application/json',
  },
});

// Request Interceptor: Attach Spring Boot JWT Token to ASP.NET Requests
dotnetApi.interceptors.request.use(
  (config) => {
    // The JWT token generated by Spring Boot (stored during login)
    const token = localStorage.getItem('token');
    
    // ASP.NET Core expects standard Bearer format
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }
    
    return config;
  },
  (error) => Promise.reject(error)
);

// Response Interceptor: Basic Error Handling
dotnetApi.interceptors.response.use(
  (response) => response.data,
  (error) => {
    console.error('ASP.NET API Error:', error.response?.data || error.message);
    return Promise.reject(error);
  }
);

// ============================================================================
// Plan Endpoints
// ============================================================================
export const planService = {
  getAllPlans: () => dotnetApi.get('/Plan'),
  getPlanById: (id) => dotnetApi.get(`/Plan/${id}`),
  createPlan: (data) => dotnetApi.post('/Plan', data),
  updatePlan: (id, data) => dotnetApi.put(`/Plan/${id}`, data),
  deletePlan: (id) => dotnetApi.delete(`/Plan/${id}`),
};

// ============================================================================
// Subscription Endpoints
// ============================================================================
export const subscriptionService = {
  purchaseSubscription: (data) => dotnetApi.post('/Subscription/purchase', data),
  recordProductView: (userId) => dotnetApi.post(`/Subscription/view/${userId}`),
  getRemainingViews: (userId) => dotnetApi.get(`/Subscription/remaining/${userId}`),
  checkCanViewProduct: (userId) => dotnetApi.get(`/Subscription/canview/${userId}`),
  checkIsExpired: (userId) => dotnetApi.get(`/Subscription/isexpired/${userId}`),
  getUserSubscription: (userId) => dotnetApi.get(`/Subscription/user/${userId}`),
  renewSubscription: (userId) => dotnetApi.post(`/Subscription/renew/${userId}`),
  cancelSubscription: (userId) => dotnetApi.post(`/Subscription/cancel/${userId}`),
};

// ============================================================================
// Payment Endpoints
// ============================================================================
export const paymentService = {
  getAllPayments: () => dotnetApi.get('/Payment'),
  getPaymentById: (id) => dotnetApi.get(`/Payment/${id}`),
  processPayment: (data) => dotnetApi.post('/Payment', data),
  deletePayment: (id) => dotnetApi.delete(`/Payment/${id}`),
};

// ============================================================================
// Invoice Endpoints
// ============================================================================
export const invoiceService = {
  getAllInvoices: () => dotnetApi.get('/Invoice'),
  getInvoiceById: (id) => dotnetApi.get(`/Invoice/${id}`),
  generateInvoice: (data) => dotnetApi.post('/Invoice', data),
  updateInvoice: (id, data) => dotnetApi.put(`/Invoice/${id}`, data),
  deleteInvoice: (id) => dotnetApi.delete(`/Invoice/${id}`),
};

export default dotnetApi;
